[features]
seeds = false
skip-lint = false
[programs.localnet]
game = "HFAYdSKLLVmbctEMU1fNx4nZ4a8vNFfjNacf4bjuQSiS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/brunobarros/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
